// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AttackIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/AttackIcon.vue')['default']
    BannedChampions: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/BannedChampions.vue')['default']
    BrainIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/BrainIcon.vue')['default']
    ChampionCard: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/ChampionCard.vue')['default']
    ChampionInfo: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/ChampionInfo.vue')['default']
    ChampionMastery: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/ChampionMastery.vue')['default']
    CheckMark: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/CheckMark.vue')['default']
    ChevronRight: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/ChevronRight.vue')['default']
    ChevronTop: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/ChevronTop.vue')['default']
    CrossMarkIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/CrossMarkIcon.vue')['default']
    ErrorComponent: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/ErrorComponent.vue')['default']
    HomeIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/HomeIcon.vue')['default']
    LiveGame: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/LiveGame.vue')['default']
    LiveGameTeamInfo: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/LiveGameTeamInfo.vue')['default']
    MagicIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/MagicIcon.vue')['default']
    MatchHistoryInfo: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/MatchHistoryInfo.vue')['default']
    MatchHistorySummoners: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/MatchHistorySummoners.vue')['default']
    MatchHistoryTeam: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/MatchHistoryTeam.vue')['default']
    MatchHistoryTeamDataTable: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/MatchHistoryTeamDataTable.vue')['default']
    MenuIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/MenuIcon.vue')['default']
    MobileSideBar: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/MobileSideBar.vue')['default']
    OkIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/OkIcon.vue')['default']
    ReloadPWA: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/ReloadPWA.vue')['default']
    SearchForSummoner: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/SearchForSummoner.vue')['default']
    ShieldIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/ShieldIcon.vue')['default']
    StatisticsIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/StatisticsIcon.vue')['default']
    StatsIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/StatsIcon.vue')['default']
    StatusIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/StatusIcon.vue')['default']
    SummonersInfo: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/SummonersInfo.vue')['default']
    SummonersRankedInfo: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/SummonersRankedInfo.vue')['default']
    SummonersTable: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/SummonersTable.vue')['default']
    TheFooter: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/TheFooter.vue')['default']
    WarningIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/WarningIcon.vue')['default']
    YummiIcon: typeof import('C:/Users/Adnan Kreiker/Documents/Demacia/src/components/Icons/YummiIcon.vue')['default']
  }
}

export { }
