// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AttackIcon: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/AttackIcon.vue')['default']
    BrainIcon: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/BrainIcon.vue')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonScooter: typeof import('~icons/carbon/scooter')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CheckMark: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/CheckMark.vue')['default']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Footer: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/Footer.vue')['default']
    MagicIcon: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/MagicIcon.vue')['default']
    README: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/README.md')['default']
    ShieldIcon: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/ShieldIcon.vue')['default']
    SwordIcon: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/SwordIcon.vue')['default']
    WarningIcon: typeof import('C:/Users/Adnan Kreiker/Documents/lol/my-vitespa-app/src/components/WarningIcon.vue')['default']
  }
}

export { }
