// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AttackIcon: typeof import('./components/Icons/AttackIcon.vue')['default']
    BannedChampions: typeof import('./components/BannedChampions.vue')['default']
    BrainIcon: typeof import('./components/Icons/BrainIcon.vue')['default']
    ChampionCard: typeof import('./components/ChampionCard.vue')['default']
    ChampionInfo: typeof import('./components/Icons/ChampionInfo.vue')['default']
    ChampionMastery: typeof import('./components/ChampionMastery.vue')['default']
    CheckMark: typeof import('./components/Icons/CheckMark.vue')['default']
    ChevronRight: typeof import('./components/Icons/ChevronRight.vue')['default']
    ChevronTop: typeof import('./components/Icons/ChevronTop.vue')['default']
    CrossMarkIcon: typeof import('./components/Icons/CrossMarkIcon.vue')['default']
    ErrorComponent: typeof import('./components/ErrorComponent.vue')['default']
    FeaturedGamesIcon: typeof import('./components/Icons/FeaturedGamesIcon.vue')['default']
    FeaturedGamesTimeSlot: typeof import('./components/FeaturedGamesTimeSlot.vue')['default']
    FilterComponent: typeof import('./components/FilterComponent.vue')['default']
    HomeIcon: typeof import('./components/Icons/HomeIcon.vue')['default']
    LiveGame: typeof import('./components/LiveGame.vue')['default']
    LiveGameTeamInfo: typeof import('./components/LiveGameTeamInfo.vue')['default']
    MagicIcon: typeof import('./components/Icons/MagicIcon.vue')['default']
    MatchHistoryInfo: typeof import('./components/MatchHistoryInfo.vue')['default']
    MatchHistorySummoners: typeof import('./components/MatchHistorySummoners.vue')['default']
    MatchHistoryTeam: typeof import('./components/MatchHistoryTeam.vue')['default']
    MatchHistoryTeamDataTable: typeof import('./components/MatchHistoryTeamDataTable.vue')['default']
    MenuIcon: typeof import('./components/Icons/MenuIcon.vue')['default']
    MobileSideBar: typeof import('./components/MobileSideBar.vue')['default']
    OkIcon: typeof import('./components/Icons/OkIcon.vue')['default']
    RefreshIcon: typeof import('./components/Icons/RefreshIcon.vue')['default']
    ReloadPWA: typeof import('./components/ReloadPWA.vue')['default']
    SearchForSummoner: typeof import('./components/SearchForSummoner.vue')['default']
    ShieldIcon: typeof import('./components/Icons/ShieldIcon.vue')['default']
    StatisticsIcon: typeof import('./components/Icons/StatisticsIcon.vue')['default']
    StatsIcon: typeof import('./components/Icons/StatsIcon.vue')['default']
    StatusIcon: typeof import('./components/Icons/StatusIcon.vue')['default']
    SummonersInfo: typeof import('./components/SummonersInfo.vue')['default']
    SummonersRankedInfo: typeof import('./components/SummonersRankedInfo.vue')['default']
    SummonersTable: typeof import('./components/SummonersTable.vue')['default']
    SummonersTableLambda: typeof import('./components/SummonersTableLambda.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    VercelLogo: typeof import('./components/Icons/VercelLogo.vue')['default']
    WarningIcon: typeof import('./components/Icons/WarningIcon.vue')['default']
    YummiIcon: typeof import('./components/Icons/YummiIcon.vue')['default']
  }
}

export { }
